from .image_detail import ImageDetail
from .configure_keyboard_shortcut import ConfigureKeyboardShortcut
from .configure_font import ConfigureFont
#from .video_player import VideoPlayer
from .main_messagebox import MainMessagebox
from .help_page import HelpPage
from .import_data import ImportData
from .login_form import LoginForm
from .deleted_images import DeletedImages
